#----------------------------------------------
# BECOME: yes
# VAULT: no
#----------------------------------------------
---
- name: Proxmox - SSH main sshd config file
  hosts: '{{ HOSTS | default("localhost") }}'
  gather_facts: true
  gather_subset:
    - '!all'

  pre_tasks:
    - name: Assertions - OS
      ansible.builtin.assert:
        that:
          - ansible_facts.os_family == 'Debian'

  tasks:
    - name: Create main sshd config file
      become: true
      ansible.builtin.copy:
        content: '{{ __etc_ssh_sshd_config_content }}'
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'
      vars:
        __etc_ssh_sshd_config_content: |
          Include /etc/ssh/sshd_config.d/*.conf


    - name: Restart ssh server
      become: true
      ansible.builtin.service:
        name: ssh
        state: restarted

